<?php

/**
 * EmailEngine PHP SDK Example
 *
 * This file demonstrates usage of the modernized EmailEngine PHP SDK.
 */

require __DIR__ . '/vendor/autoload.php';

use Postalsys\EmailEnginePhp\EmailEngine;
use Postalsys\EmailEnginePhp\Exceptions\EmailEngineException;
use Postalsys\EmailEnginePhp\Exceptions\NotFoundException;

// =============================================================================
// Modern API (Recommended)
// =============================================================================

$client = new EmailEngine(
    accessToken: '3eb50ef80efb67885afb43844df8ae01e4eecb99c4defac3aa37ec5b8b4f1339',
    baseUrl: 'http://127.0.0.1:3000',
    serviceSecret: 'a23da152f5b88543f52420a0de0e0eb6',
    redirectUrl: 'http://127.0.0.1:5000/handler.php',
);

// Generate hosted authentication URL
echo "Authentication URL:\n";
echo $client->getAuthenticationUrl(['account' => null]);
echo "\n\n";

// Configure webhooks
$client->settings->setWebhooks([
    'enabled' => true,
    'url' => 'http://127.0.0.1:5000/webhooks.php',
    'events' => ['*'],
    'headers' => ['Received', 'List-ID'],
    'text' => 1024 * 1024,
]);

// Get webhook settings
echo "Webhook Settings:\n";
print_r($client->settings->getWebhooks());

// Get server statistics
echo "\nServer Statistics:\n";
print_r($client->stats->get());

// Register a new account
try {
    $accountResult = $client->accounts->create([
        'account' => null, // auto-generated by EmailEngine
        'name' => 'Andris Reinman',
        'email' => 'andris@ekiri.ee',
        'imap' => [
            'auth' => ['user' => 'andris', 'pass' => 'secretvalue'],
            'host' => 'turvaline.ekiri.ee',
            'port' => 993,
            'secure' => true,
        ],
        'smtp' => [
            'auth' => ['user' => 'andris', 'pass' => 'secretvalue'],
            'host' => 'turvaline.ekiri.ee',
            'port' => 465,
            'secure' => true,
        ],
    ]);

    $accountId = $accountResult['account'];
    echo "\nCreated account: {$accountId}\n";

    // Wait for account to connect
    $connected = false;
    while (!$connected) {
        sleep(1);
        $accountInfo = $client->accounts->get($accountId);

        if ($accountInfo['state'] === 'connected') {
            $connected = true;
            echo "Account {$accountId} is connected\n";
        } else {
            echo "Account {$accountId} is {$accountInfo['state']}...\n";
        }
    }

    // List mailboxes
    echo "\nMailboxes:\n";
    $mailboxes = $client->mailboxes->list($accountId);
    foreach ($mailboxes['mailboxes'] as $mailbox) {
        echo "  - {$mailbox['path']}\n";
    }

    // Send an email
    echo "\nSending email...\n";
    $submitResult = $client->messages->submit($accountId, [
        'from' => ['name' => 'Andris Reinman', 'address' => 'andris@ekiri.ee'],
        'to' => [['name' => 'Ethereal', 'address' => 'andris@ethereal.email']],
        'subject' => 'Test message',
        'text' => 'Hello from myself!',
        'html' => '<p>Hello from myself!</p>',
    ]);

    echo "Email sent!\n";
    print_r($submitResult);

    // List recent messages
    echo "\nRecent messages in INBOX:\n";
    $messages = $client->messages->list($accountId, [
        'path' => 'INBOX',
        'pageSize' => 5,
    ]);
    foreach ($messages['messages'] as $msg) {
        echo "  - {$msg['subject']} (from: {$msg['from'][0]['address']})\n";
    }

} catch (NotFoundException $e) {
    echo "Not found: " . $e->getMessage() . "\n";
} catch (EmailEngineException $e) {
    echo "Error: " . $e->getMessage() . "\n";
    if ($e->getErrorCode()) {
        echo "Error code: " . $e->getErrorCode() . "\n";
    }
}

// =============================================================================
// Legacy API (for backward compatibility)
// =============================================================================

echo "\n\n--- Legacy API Example ---\n\n";

// Old-style initialization still works
use EmailEnginePhp\EmailEngine as LegacyEmailEngine;

$ee = new LegacyEmailEngine([
    'access_token' => '3eb50ef80efb67885afb43844df8ae01e4eecb99c4defac3aa37ec5b8b4f1339',
    'service_secret' => 'a23da152f5b88543f52420a0de0e0eb6',
    'ee_base_url' => 'http://127.0.0.1:3000/',
    'redirect_url' => 'http://127.0.0.1:5000/handler.php',
]);

// Old method names still work (deprecated but functional)
echo "Legacy auth URL: " . $ee->get_authentication_url(['account' => null]) . "\n";
echo "Legacy webhook settings:\n";
print_r($ee->get_webhook_settings());
