<?php

require __DIR__ . '/vendor/autoload.php';

use EmailEnginePhp\EmailEngine;

$ee = new EmailEngine(array(
    "access_token" => "3eb50ef80efb67885afb43844df8ae01e4eecb99c4defac3aa37ec5b8b4f1339",
    "service_secret" => "a23da152f5b88543f52420a0de0e0eb6",
    "ee_base_url" => "http://127.0.0.1:3000/",
    "redirect_url" => "http://127.0.0.1:5000/handler.php",
));

echo $ee->get_authentication_url(array("account" => null));

echo "\n";

$ee->set_webhook_settings(array(
    "enabled" => true,
    "url" => "http://127.0.0.1:5000/webhooks.php",
    "events" => array("*"),
    "headers" => array("Received", "List-ID"),
    "text" => 1024 * 1024,
));

print_r($ee->get_webhook_settings());

$server_stats = $ee->request('get', '/v1/stats');

print_r($server_stats);

// Register a new account
$account_response = $ee->request('post', '/v1/account', array(
    'account' => null, // autogenerated by EmailEngine
    'name' => 'Andris Reinman',
    'email' => 'andris@ekiri.ee',
    'imap' => array(
        'auth' => array(
            'user' => 'andris',
            'pass' => 'secretvalue',
        ),
        'host' => 'turvaline.ekiri.ee',
        'port' => 993,
        'secure' => true,
    ),
    'smtp' => array(
        'auth' => array(
            'user' => 'andris',
            'pass' => 'secretvalue',
        ),
        'host' => 'turvaline.ekiri.ee',
        'port' => 465,
        'secure' => true,
    ),
));

$account_id = $account_response['account'];

$account_connected = false;
while (!$account_connected) {
    sleep(1);
    $account_info = $ee->request('get', "/v1/account/$account_id");
    if ($account_info["state"] == "connected") {
        $account_connected = true;
        echo "Account $account_id is connected\n";
    } else {
        echo "Account $account_id is ${account_info['state']}...\n";
    }
}

// send an email using this account
$submit_response = $ee->request('post', "/v1/account/$account_id/submit", array(
    "from" => array(
        "name" => "Andris Reinman",
        "address" => "andris@ekiri.ee",
    ),
    "to" => array(
        array(
            "name" => "Ethereal",
            "address" => "andris@ethereal.email",
        ))
    ,
    "subject" => "Test message",
    "text" => "Hello from myself!",
    "html" => "<p>Hello from myself!</p>",
));

print_r($submit_response);
